import type { Metadata } from "next";

import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local";

import { ProviderLayout } from "@/provider";
import { BottomNavigation } from "@/components/module";
import { Box } from "@mui/material";

import "../globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Vazirmatn({ subsets: ["arabic"] });
const allFont = localFont({
  src: [
    {
      path: "../public/font/Qs_Iranyekan medium.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "next-app",
  description: "Generated by create next app",
};

type propsLayout = Readonly<{
  children: React.ReactNode;
  items: React.ReactNode;
  teams: React.ReactNode;
}>;

export default function RootLayout({ children, items, teams }: propsLayout) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${inter.className} ${allFont.className}`}
        style={{
          backgroundColor: "#cccccc",
          padding: 0,
          margin: 0,
          display: "flex",
          justifyContent: "center",
        }}
      >
        <ProviderLayout>
          <Box
            sx={{
              height: "100vh",
              width: { xs: "100%", sm: "450px" },
              backgroundColor: "#F2F4F8",
              overflow: "hidden",
              overflowY: "scroll",
              "&::-webkit-scrollbar": {
                width: "4px",
              },
              "&::-webkit-scrollbar-thumb": {
                backgroundColor: "#0000001f !important",
              },
            }}
            p={0}
            m={0}
          >
            <Box pb={15}>{children}</Box>
            <Box
              position={"relative"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
              bottom={10}
            >
              {/* <BottomNavigation /> */}
            </Box>
          </Box>
        </ProviderLayout>
      </body>
    </html>
  );
}
